name: Mileno
favicon: null
layout_spectrum: 0.99813
typography_spectrum: 0.82985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1462ac'
    - '#3d92d2'
    - '#b8cfe5'
    - '#dce7f3'
  brandStrength: 0.7010376458056271
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
